version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cinemacalc
      POSTGRES_DB: CinemaCalcDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: